2019-11-06 18:01:24.915 parsl.dataflow.dflow:83 [DEBUG]  Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    data_management_max_threads=10, 
    executors=[ThreadPoolExecutor(
        label='threads', 
        managed=True, 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    )], 
    initialize_logging=True, 
    lazy_errors=True, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    run_dir='runinfo', 
    strategy='simple', 
    usage_tracking=False
)
2019-11-06 18:01:24.915 parsl.dataflow.dflow:84 [INFO]  Parsl version: 0.9.0
2019-11-06 18:01:24.916 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: False
2019-11-06 18:01:24.916 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
2019-11-06 18:01:24.916 parsl.dataflow.dflow:110 [INFO]  Run id is: 679891ea-7f9f-44b3-91a7-bc76215f4313
2019-11-06 18:01:24.966 parsl.dataflow.memoization:52 [INFO]  App caching initialized
2019-11-06 18:01:24.966 parsl.dataflow.strategy:125 [DEBUG]  Scaling strategy: simple
2019-11-06 18:01:24.967 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.968 parsl.dataflow.dflow:708 [INFO]  Task 0 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.968 parsl.dataflow.dflow:714 [DEBUG]  Task 0 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57eaca4940 state=pending>>
2019-11-06 18:01:24.968 parsl.dataflow.dflow:452 [INFO]  Task 0 launched on executor threads
2019-11-06 18:01:24.968 parsl.dataflow.dflow:288 [INFO]  Task 0 completed
2019-11-06 18:01:24.968 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.968 parsl.dataflow.dflow:708 [INFO]  Task 1 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.968 parsl.dataflow.dflow:714 [DEBUG]  Task 1 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57eac15358 state=pending>>
2019-11-06 18:01:24.969 parsl.dataflow.dflow:452 [INFO]  Task 1 launched on executor threads
2019-11-06 18:01:24.969 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.969 parsl.dataflow.dflow:257 [DEBUG]  Task 1 failed
2019-11-06 18:01:24.969 parsl.dataflow.dflow:279 [ERROR]  Task 1 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.970 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.970 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.970 parsl.dataflow.dflow:708 [INFO]  Task 2 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.970 parsl.dataflow.dflow:714 [DEBUG]  Task 2 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57eac15978 state=pending>>
2019-11-06 18:01:24.971 parsl.dataflow.dflow:452 [INFO]  Task 2 launched on executor threads
2019-11-06 18:01:24.971 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.971 parsl.dataflow.dflow:708 [INFO]  Task 3 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.971 parsl.dataflow.dflow:714 [DEBUG]  Task 3 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57eac30208 state=pending>>
2019-11-06 18:01:24.971 parsl.dataflow.dflow:452 [INFO]  Task 3 launched on executor threads
2019-11-06 18:01:24.971 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.971 parsl.dataflow.dflow:708 [INFO]  Task 4 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.971 parsl.dataflow.dflow:714 [DEBUG]  Task 4 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57eac303c8 state=pending>>
2019-11-06 18:01:24.971 parsl.dataflow.dflow:452 [INFO]  Task 4 launched on executor threads
2019-11-06 18:01:24.972 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.972 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.972 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.973 parsl.dataflow.dflow:257 [DEBUG]  Task 2 failed
2019-11-06 18:01:24.973 parsl.dataflow.dflow:257 [DEBUG]  Task 3 failed
2019-11-06 18:01:24.973 parsl.dataflow.dflow:708 [INFO]  Task 5 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.973 parsl.dataflow.dflow:279 [ERROR]  Task 2 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.973 parsl.dataflow.dflow:279 [ERROR]  Task 3 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.973 parsl.dataflow.dflow:714 [DEBUG]  Task 5 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57eac30b70 state=pending>>
2019-11-06 18:01:24.974 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.974 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.974 parsl.dataflow.dflow:452 [INFO]  Task 5 launched on executor threads
2019-11-06 18:01:24.975 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.975 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.976 parsl.dataflow.dflow:257 [DEBUG]  Task 4 failed
2019-11-06 18:01:24.976 parsl.dataflow.dflow:257 [DEBUG]  Task 5 failed
2019-11-06 18:01:24.976 parsl.dataflow.dflow:279 [ERROR]  Task 4 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.976 parsl.dataflow.dflow:279 [ERROR]  Task 5 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.977 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.977 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.977 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.977 parsl.dataflow.dflow:708 [INFO]  Task 6 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.978 parsl.dataflow.dflow:714 [DEBUG]  Task 6 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57e93bb5f8 state=pending>>
2019-11-06 18:01:24.978 parsl.dataflow.dflow:452 [INFO]  Task 6 launched on executor threads
2019-11-06 18:01:24.978 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.978 parsl.dataflow.dflow:708 [INFO]  Task 7 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.978 parsl.dataflow.dflow:714 [DEBUG]  Task 7 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57e93bb828 state=pending>>
2019-11-06 18:01:24.978 parsl.dataflow.dflow:452 [INFO]  Task 7 launched on executor threads
2019-11-06 18:01:24.978 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.979 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.979 parsl.dataflow.dflow:257 [DEBUG]  Task 6 failed
2019-11-06 18:01:24.979 parsl.dataflow.dflow:257 [DEBUG]  Task 7 failed
2019-11-06 18:01:24.979 parsl.dataflow.dflow:279 [ERROR]  Task 6 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.979 parsl.dataflow.dflow:279 [ERROR]  Task 7 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.980 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.980 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.981 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.981 parsl.dataflow.dflow:708 [INFO]  Task 8 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.981 parsl.dataflow.dflow:714 [DEBUG]  Task 8 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57e93c1128 state=pending>>
2019-11-06 18:01:24.981 parsl.dataflow.dflow:452 [INFO]  Task 8 launched on executor threads
2019-11-06 18:01:24.981 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:01:24.981 parsl.dataflow.dflow:708 [INFO]  Task 9 submitted for App fun_1, waiting on tasks []
2019-11-06 18:01:24.981 parsl.dataflow.dflow:714 [DEBUG]  Task 9 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f57e93c1278 state=pending>>
2019-11-06 18:01:24.981 parsl.dataflow.dflow:452 [INFO]  Task 9 launched on executor threads
2019-11-06 18:01:24.982 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.982 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.982 parsl.dataflow.dflow:257 [DEBUG]  Task 8 failed
2019-11-06 18:01:24.982 parsl.dataflow.dflow:864 [INFO]  DFK cleanup initiated
2019-11-06 18:01:24.983 parsl.dataflow.dflow:257 [DEBUG]  Task 9 failed
2019-11-06 18:01:24.983 parsl.dataflow.dflow:279 [ERROR]  Task 8 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.983 parsl.dataflow.dflow:750 [INFO]  Summary of tasks in DFK:
2019-11-06 18:01:24.983 parsl.dataflow.dflow:279 [ERROR]  Task 9 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:01:24.983 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.983 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.done: 0
2019-11-06 18:01:24.984 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:01:24.984 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.failed: 1, 2, 3, 4, 5, 6, 7, 8
2019-11-06 18:01:24.984 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.launched: 9
2019-11-06 18:01:24.984 parsl.dataflow.dflow:788 [INFO]  End of summary
2019-11-06 18:01:24.984 parsl.dataflow.dflow:888 [INFO]  Terminating flow_control and strategy threads
2019-11-06 18:01:24.984 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-06 18:01:24.984 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-06 18:01:24.985 parsl.dataflow.dflow:920 [INFO]  DFK cleanup complete
